---
title: "WHIOS Descriptive"
author: "Yi Zhao"
date: "3/20/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars, echo = FALSE}
library(haven)
library(reshape2)
library(ggplot2)
library(corrplot)

#Read in data
setwd("/Users/Yi/Box Sync/BKNR/WHIOS/WHI_OS_2014b/WHI_OS_2014a/data/whi/sas_data")
nutrients<-read_sas("f60_nutr_os_pub.sas7bdat")
ffq<-read_sas("f60_item_os_pub.sas7bdat")
outcome<-read_sas("f80_os_pub.sas7bdat") #CVD outcome: outc_adj_os_pub; physical measuremnet outcome: f80_os_pub
demo<-read_sas("dem_os_pub.sas7bdat")

#########STEP ONE: Generate dataset#########
#Clean FFQ datasets
  # only keep anual visit (instead of baseline for recruitment), visit year=3, closest to designed visit time, status=600 kcal <= Energy <= 5000 kcal
  ffq<-ffq[ffq$F60VTYP==3 & ffq$F60VY==3 & ffq$F60VCLO==1 & ffq$STATUS==3,] 
  foodgroup<-c("ID","FRUITS", "VEGTABLS", "FRUVEG", "FISH", "REDMEAT","POULTRY", "SOY", "NUTS","GRAINS","WHLGRNS", "MILKS","DAIRY","WINE","BEER", "LIQUOR", "POP","COFFEE") 
  ffq<-ffq[foodgroup]
  
#Clean nutrients
nutrients<-nutrients[nutrients$F60VTYP==3 & nutrients$F60VY==3 & nutrients$F60VCLO==1,]

#Clean outcome dataset
  # only keep 1) visit type=anual visit, visit year=3, closest to visit year
outcome<-outcome[outcome$F80VTYP==3 & outcome$F80VY==3 & outcome$F80VCLO==1,]

#Merge datasets
#outcome + demographical data
combine1<-merge(demo,outcome, by="ID")
# + nutrients dataset
combine2<-merge(nutrients,combine1, by="ID")
# + ffq dataset
combine3<-merge(ffq,combine2, by="ID")

#delete missing value
combine_nomiss<-na.omit(combine3)

#########STEP TWO: descriptive analysis of the dataset #########
#distribution of the EXPOSURE
ggplot(data = melt(combine_nomiss[foodgroup[-1]]), mapping = aes(x = value)) + geom_histogram(bins = 15) + facet_wrap(~variable, scales = 'free_x') + 
  labs(title="distribution of exposure", x="servings per day")
summary(combine_nomiss[foodgroup[-1]])

#add value 1 to each exposure
plus_exp<-data.frame(lapply(foodgroup[-1],function(x){combine_nomiss[,x]+1}))
names(plus_exp)<-paste0("plus_",foodgroup[-1])
combine_nomiss<-cbind(combine_nomiss,plus_exp)  


#ln-transform all EXPOSURE variables
log_plus_exp<-data.frame(lapply(names(plus_exp),function(x){log(combine_nomiss[,x])}))
names(log_plus_exp)<-paste0("log_",names(plus_exp))
combine_nomiss<-cbind(combine_nomiss,log_plus_exp) 

#distribution of the log-transformed exposures
ggplot(data = melt(log_plus_exp), mapping = aes(x = value))  + geom_histogram(bins = 15) + facet_wrap(~variable, scales = 'free_x')  + 
  labs(title="Distribution of log_(exposure+1)", x="log_(servings+1 per day)") 

#Correlation of the EXPOSURE
corrplot(cor(combine_nomiss[foodgroup[-1]]), type = "upper", order = "hclust", tl.col = "black", tl.srt = 45)
# coll<-cor(ffq)
# coll[lower.tri(coll,diag=TRUE)]=NA  #Prepare to drop duplicates and meaningless information
# coll=as.data.frame(as.table(coll))  #Turn into a 3-column table
# coll=na.omit(coll)  #Get rid of the junk we flagged above
# coll=coll[order(-abs(coll$Freq)),]
# coll

#distribution of the OUTCOMES 
ggplot(data = melt(combine_nomiss[c("SYST")]), mapping = aes(x = value)) + 
  geom_histogram(bins = 20) + facet_wrap(~variable, scales = 'free_x') + 
  labs(title="Distribution of Outcome",x="Systolic BP")

#distribution of the COVARIATES
ggplot(data = melt(combine_nomiss[c("AGE","BMIX","INCOME")]), mapping = aes(x = value)) + 
  geom_histogram(bins = 20) + facet_wrap(~variable, scales = 'free_x') + 
  ggtitle("Distribution of covariates")

#linearity between COVARIATES and OUTCOME (scatterplot+linear regression+lowess)---maybe do it in a loop
combine_nomiss$f.INCOME<-as.factor(combine_nomiss$INCOME)
#age
plot(combine_nomiss$SYST~combine_nomiss$AGE,main="SBP~Age", col="grey")
abline(lm(SYST~AGE,data=combine_nomiss),col="pink")
lines(lowess(combine_nomiss$AGE,combine_nomiss$SYST),col="green")
legend(67,210,legend=c("regression","lowess"),col=c("pink","green"),lty = c(1,1))
#BMI
plot(combine_nomiss$SYST~combine_nomiss$BMIX,main="SBP~BMI", col="grey")
abline(lm(SYST~BMIX,data=combine_nomiss),col="pink")
lines(lowess(combine_nomiss$BMIX,combine_nomiss$SYST),col="green")
legend(40,210,legend=c("regression","lowess"),col=c("pink","green"),lty = c(1,1))
#income (categorical)
plot(combine_nomiss$SYST~combine_nomiss$f.INCOME,main="SBP~INCOME", col="pink")
#income (treating categories as continuous)
plot(combine_nomiss$SYST~combine_nomiss$INCOME,main="SBP~INCOME(cat)", col="grey")
abline(lm(SYST~INCOME,data=combine_nomiss),col="pink")
lines(lowess(combine_nomiss$INCOME,combine_nomiss$SYST),col="green")
legend(5.5,210,legend=c("regression","lowess"),col=c("pink","green"),lty = c(1,1))

#Run a multivarable regression on full dataset
summary(lm(SYST~FRUITS+VEGTABLS+FISH+REDMEAT+POULTRY+SOY+NUTS+GRAINS+WHLGRNS+MILKS+DAIRY+WINE+BEER+LIQUOR+POP+COFFEE
           +AGE+BMIX,data=combine_nomiss))



#########STEP THREE: prepare for sample dataset#########
#take a random sample from the dataset
set.seed(123)
sample<-combine_nomiss[sample(1:nrow(combine_nomiss),2000, replace=FALSE), ]

#sample regression
summary(lm(SYST~FRUITS+VEGTABLS+FISH+REDMEAT+POULTRY+SOY+NUTS+GRAINS+WHLGRNS+MILKS+DAIRY+WINE+BEER+LIQUOR+POP+COFFEE
           +AGE+BMIX,data=sample)) #exclude the fruit and veggie combined group as high collinarity
print(summary(lm(SYST~FRUITS+VEGTABLS+FISH+REDMEAT+POULTRY+SOY+NUTS+GRAINS+WHLGRNS+MILKS+DAIRY+WINE+BEER+LIQUOR+POP+COFFEE +
                   AGE+BMIX,data=sample)))


```


